name: Upload Website

on:
  push:
    branches:
    - main
  workflow_dispatch: 
    inputs: 
     envFile:
      description: Env file to deploy
      type: text
      required: false
      default: '.env.production'

jobs:
  DeployToAWS: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    - name: Install Node
      run: | 
            sudo apt update
            curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
            sudo apt -y install nodejs
    - name: Build
      run: | 
            if [ -z "${{inputs.envFile}}" ] 
            then 
             ENV=.env.production
            else 
             ENV=${{inputs.envFile}}
            fi
            npm install --legacy-peer-deps && \
            npm i -g env-cmd && \
            CI=false env-cmd -f ${ENV} npm run build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build/'      # optional: defaults to entire repository
